import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-Commerce Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>

      {/* <ClerkProvider>
       */}
          {/* <SignedOut>
            <SignInButton />           
          </SignedOut>          
          <SignedIn>            
            <UserButton />            
          </SignedIn> */}
          <Navbar />
          {children}
{/*       
    </ClerkProvider> */}


        {/* <Navbar /> */}
        
        {/* {children} */}
        <Footer />
        </body>
    </html>
    </ClerkProvider>
  );
}





// "use client"
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Navbar from "./components/navbar";
// import Footer from "./components/footer";
// import { appWithTranslation } from "next-i18next";



// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "E-Commerce Website",
//   description: "Generated by create next app",
// };

// function RootLayout({ children }: { children: React.ReactNode }) {

//   return (
//     <html lang="en">
//       <body >

//         <Navbar />
        
//         {children}
//         <Footer />
//         </body>
//     </html>
//   );
// }

// export default appWithTranslation(RootLayout);